# src/docker-compose.yml
version: "3.9"

services:
  # sqlserver:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=Nam@15112003
  #   ports:
  #     - "1432:1433"
  #   volumes:
  #     - sqlserver-data:/var/opt/mssql
  iam_api:
    build:
      context: . # src/ là gốc
      dockerfile: Services/SRSS.IAM/SRSS.IAM.API/Dockerfile # Từ src/
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__SRSS_IAM_DB=Server=host.docker.internal;Database=SRSS.IAM;User Id=sa;Password=12345;TrustServerCertificate=True;
      - ConnectionStrings__Redis=host.docker.internal:6379
    networks:
      - proxybackend
  project_api:
    build:
      context: . # src/ là gốc
      dockerfile: Services/SRSS.Project/SRSS.Project.API/Dockerfile # Từ src/
    ports:
      - "8082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__SRSS_Project_DB=Server=host.docker.internal;Database=SRSS.Project;User Id=sa;Password=12345;TrustServerCertificate=True;
      - ConnectionStrings__Redis=host.docker.internal:6379
    networks:
      - proxybackend
  api-gateway:
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile
    ports:
      - "7232:443"
      - "5103:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=7232
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ../https:/https:ro # LÊN 1 cấp 
    depends_on:
      - iam_api
      - project_api
    networks:
      - proxybackend

volumes:
  sqlserver-data:
  
networks:
  proxybackend:
    name: proxybackend
    driver: bridge
