# src/docker-compose.yml
version: "3.9"

services:
  iam_api:
    build:
      context: . # src/ là gốc
      dockerfile: Services/SRSS.IAM/SRSS.IAM.API/Dockerfile # Từ src/
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__SRSS_IAM_DB=Host=${SRSS_IAM_DB_HOST};Port=5432;Username=${SRSS_IAM_DB_USERNAME};Password=${SRSS_IAM_DB_PASSWORD};Database=${SRSS_IAM_DB_NAME}
      - ConnectionStrings__Redis=${REDIS_HOST}:6379
    networks:
      - proxybackend
  project_api:
    build:
      context: . # src/ là gốc
      dockerfile: Services/SRSS.Project/SRSS.Project.API/Dockerfile # Từ src/
    ports:
      - "8082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__SRSS_Project_DB=Host=${SRSS_Project_DB_HOST};Port=5432;Username=${SRSS_Project_DB_USERNAME};Password=${SRSS_Project_DB_PASSWORD};Database=${SRSS_Project_DB_NAME}
      - ConnectionStrings__Redis=${REDIS_HOST}:6379
    networks:
      - proxybackend
  api-gateway:
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile
    ports:
      - "7232:443"
      - "5103:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=7232
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ../https:/https:ro # LÊN 1 cấp
    depends_on:
      - iam_api
      - project_api
    networks:
      - proxybackend

volumes:
  sqlserver-data:

networks:
  proxybackend:
    name: proxybackend
    driver: bridge
